language: node_js
sudo: false
node_js:
   - '8'
env:
   global:
      - SAUCE_CONNECT_VERSION=4.4.12
   matrix:
      - BROWSER="chrome"
      - BROWSER="firefox"
      - BROWSER="internet explorer"
      - BROWSER="safari"
      - BROWSER="sauce"
branches:
   except:
      - /^feature\/.*$/

notifications:
   irc:
      channels: "chat.freenode.net#laxarjs"
      template: "%{repository_slug} (%{commit}) [%{branch}]: %{message}"

script:
   - |
      if [ $BROWSER == "sauce" ]; then
         travis_wait 30 nightwatch-tests/runtests
      else
         travis_wait yarn test
      fi
