language: node_js

script:
  - DPRO=local ./node_modules/.bin/magellan --sauce_create_tunnels --bs_create_tunnel --external_build_id=$TRAVIS_BUILD_ID --bail_time=${MAGELLAN_INDIVIDUAL_TEST_BAIL_TIME} --profile all

node_js:
  - v7
  - v6
  - v5
  - v4

# Use container-based Travis infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  hosts:
    - travis.dev

before_install:
  # ensure latest npm installed.
  - npm install -g npm
  - npm --version
  - export MAGELLAN_BUILD_NAME=${TRAVIS_JOB_ID}_${TRAVIS_JOB_NUMBER}
  - export MAGELLAN_BUILD_ID=`date +%s`
  - export SAUCE_CONNECT_VERSION=4.4.1
  - export MOCK_HOSTNAME=travis.dev
